import MainHero from '@/components/homepage/main-hero';
import LoaderWrap from '@/components/ui/loader-wrap';
import Image from 'next/image';

export default function Home() {
  const gifs = [
    {
      src: '/app/app-view.gif',
      title: 'App Overview',
      description:
        'The app is a hosting management tool used to organize and manage property reservations.',
    },
    {
      src: '/app/creating-new-user.gif',
      title: 'Sign In',
      description:
        "You can sign in easily using an email and password. If you don't have an account, the app will automatically create one for you.",
    },
    {
      src: '/app/creating-and-editing-property.gif',
      title: 'Properties',
      description:
        'To create a reservation, the user first needs to create a property. After that, the user can edit and delete properties and view their reservations.',
    },
    {
      src: '/app/creating-and-editing-reservation.gif',
      title: 'Reservations',
      description:
        'Once a property is created, the user can create and edit reservations, modify dates, and remove them. However, reservations for a property cannot overlap.',
    },
    {
      src: '/app/stats.gif',
      title: 'Stats',
      description:
        'The user can view stats about properties, monitor the number of reservations for a month, track the revenue generated by a property, and compare it with previous months.',
    },
  ];

  return (
    <>
      <LoaderWrap />

      <MainHero />
      <div className="container mx-auto mt-8 px-4 slide-up">
        {gifs.map((gif, index) => (
          <div key={index} className="flex flex-col mb-8">
            <div className="mb-4">
              <h2 className="text-2xl font-bold">{gif.title}</h2>
              <p className="text-gray-700">{gif.description}</p>
            </div>
            <div className="relative w-full h-64 md:h-96 lg:h-[850px]">
              <Image
                src={gif.src}
                alt={gif.title}
                layout="fill"
                objectFit="cover"
                priority
              />
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
